# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 658e9e9c94343533ce306de36dff3f6061e9ec1b3d9602349615e0469e85b9f3e48665a956290eabab3d1dda2db347d3886713980bfcd707b269d85c8dc08d5a

test:
  secret_key_base: 5f54d20f6a262281c128a1ce689364d75a9e46c2d4b8b3b0f8c0e8cb6c335c6cb693050957b3219f5e33189c07a0b2086e56a990bc87c406de3d936408aaf9df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
